apiVersion: v1
kind: Service
metadata:
  name: api-load-balancer-service
  namespace: dev
spec:
  type: NodePort #LoadBalancer
  selector:
    component: api
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31515